"""Dev tool: write EXERCISE_INDEX.md (every exercise, its solution file and its latest
result) and the results table in README.md, from course/exercises.json,
course/model_needs.json, solutions/index.json and solutions/outputs/*/summary.json.
Safe to rerun after any run-chapter run.   python dev/exercise_index.py"""
import json
import re
from pathlib import Path

KIT = Path(__file__).resolve().parent.parent
EX = json.loads((KIT / "course/exercises.json").read_text(encoding="utf-8"))
NEEDS = json.loads((KIT / "course/model_needs.json").read_text(encoding="utf-8"))
INDEX = json.loads((KIT / "solutions/index.json").read_text(encoding="utf-8"))
OUTPUTS = KIT / "solutions/outputs"

CAPSTONES = {"C1": ("c1_support", "Customer support agent"),
             "C2": ("c2_analyst", "Natural-language data analyst"),
             "C3": ("c3_incident", "Incident triage"),
             "C4": ("c4_review", "Code review and fix agent"),
             "C5": ("c5_research", "Deep research assistant"),
             "C6": ("c6_backoffice", "Back-office workflow agent")}
KIND = {"concept": "Written answer", "run": "Run chapter code", "build": "Build",
        "test": "Write tests", "ask": "Chat with tools", "inspector": "MCP Inspector",
        "desktop": "Claude Desktop"}
MODEL = {"none": "No model", "any": "Local or Claude", "claude-rec": "Claude recommended",
         "claude": "Claude only", "desktop": "Claude Desktop"}
BEGIN, END = "<!-- results:start -->", "<!-- results:end -->"


def chapter_dir(key):
    return f"ch{int(key):02d}" if key.isdigit() else key


def solution_files():
    """Flat name (ex4_4_trace.py) -> real path in its chapter folder."""
    found = {}
    for p in (KIT / "solutions").rglob("*"):
        if p.is_file() and "_index" not in p.parts and "outputs" not in p.parts \
                and "__pycache__" not in p.parts:
            found.setdefault(p.name, p.relative_to(KIT).as_posix())
    return found


def results():
    """Exercise id -> its entry in the latest summary.json, plus the file's date."""
    out = {}
    for summary in OUTPUTS.glob("*/summary.json"):
        data = json.loads(summary.read_text(encoding="utf-8"))
        for x in data["exercises"]:
            x.setdefault("model", data.get("model", ""))
            out[x["id"]] = x
    return out


def short_model(label):
    return label.split(" (")[0] if label and label != "none" else ""


def status(x):
    if not x:
        return "not run yet"
    if x["status"] == "passed":
        m = short_model(x.get("model"))
        return f"✔ passed ({m}, {x['seconds']:.0f} s)" if m else f"✔ passed ({x['seconds']:.0f} s)"
    if x["status"] == "failed":
        return f"✘ failed ({x.get('reason') or 'see log'})"
    reason = x.get("reason") or "skipped"
    if reason.startswith("concept"):
        return "written answer"
    return "skipped: " + reason.split(":")[0].replace("|", "/")


def chapters():
    """[(key, title, [exercises])] in book order."""
    order = []
    for e in EX:
        key = e["id"].split(".")[0]
        if not order or order[-1][0] != key:
            order.append((key, e["chapter"], []))
        order[-1][2].append(e)
    return order


def tally(entries):
    t = {"passed": 0, "failed": 0, "written": 0, "skipped": 0, "not run": 0}
    for x in entries:
        if not x:
            t["not run"] += 1
        elif x["status"] in ("passed", "failed"):
            t[x["status"]] += 1
        elif (x.get("reason") or "").startswith("concept"):
            t["written"] += 1
        else:
            t["skipped"] += 1
    return t


def write_index(res, files):
    lines = ["# Exercise index", "",
             "Every exercise in the course, in book order: what kind it is, which model it "
             "needs, where its reference solution is, and its result in the latest "
             "verification run. Generated by `python dev/exercise_index.py` from the course "
             "data and `solutions/outputs/*/summary.json`; don't edit it by hand.", "",
             "Practise each exercise yourself first with `./course.sh ex <id>`, then compare "
             "with `./course.sh solution <id>`. Full instructions: [README.md](README.md).", "",
             "**Model needed:** *No model* runs offline. *Local or Claude* works with the free "
             "`qwen3.5:9b` or Claude. *Claude recommended* runs locally but works better on "
             "Claude. *Claude only* needs `PROVIDER=claude` and an API key.", "",
             "## Contents", ""]
    for key, title, _ in chapters():
        anchor = re.sub(r"[^a-z0-9 -]", "", title.lower()).replace(" ", "-")
        lines.append(f"- [{title}](#{anchor})")
    lines.append("- [Capstone projects](#capstone-projects)")
    for key, title, exercises in chapters():
        lines += ["", f"## {title}", "",
                  f"Logs: [`solutions/outputs/{chapter_dir(key)}/`](solutions/outputs/{chapter_dir(key)}/)", "",
                  "| # | Exercise | Level | Type | Model needed | Solution | Latest result |",
                  "| --- | --- | --- | --- | --- | --- | --- |"]
        for e in exercises:
            sols = [files.get(Path(f).name, f"solutions/{f}") for f in INDEX.get(e["id"], [])]
            sol = "<br>".join(f"[`{Path(s).name}`]({s})" for s in sols) or "—"
            need = MODEL.get(NEEDS.get(e["id"], {}).get("model", "any"), "Local or Claude")
            lines.append(f"| {e['id']} | {e['title']} | {e.get('level') or ''} | "
                         f"{KIND.get(e['kind'], e['kind'])} | {need} | {sol} | "
                         f"{status(res.get(e['id']))} |")
    lines += ["", "## Capstone projects", "",
              "Run a reference capstone with `./course.sh capstone <1-6>`.", "",
              "| # | Project | Folder | Latest result |", "| --- | --- | --- | --- |"]
    for key, (folder, name) in CAPSTONES.items():
        lines.append(f"| {key} | {name} | [`solutions/capstones/{folder}/`]"
                     f"(solutions/capstones/{folder}/) | {status(res.get(key))} |")
    (KIT / "EXERCISE_INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def results_table(res):
    rows, total = [], tally([])
    for key, title, exercises in chapters():
        t = tally([res.get(e["id"]) for e in exercises])
        rows.append((title, len(exercises), t))
    caps = tally([res.get(k) for k in CAPSTONES])
    rows.append(("Capstone projects C1–C6", len(CAPSTONES), caps))
    for _, _, t in rows:
        for k in total:
            total[k] += t[k]
    ran = total["passed"] + total["failed"]
    dates = sorted(json.loads(p.read_text(encoding="utf-8")).get("date", "")
                   for p in OUTPUTS.glob("*/summary.json"))
    fails = [f"**{i}** ({x['title']}: {x.get('reason')})" for i, x in res.items()
             if x["status"] == "failed"]
    out = [BEGIN,
           f"Latest verification: every exercise run with its reference solution by "
           f"`run-chapter` (runs from {dates[0][:10]} to {dates[-1][:10]}). "
           f"**{total['passed']} of {ran} runnable exercises passed "
           f"({100 * total['passed'] / max(ran, 1):.1f}%)**; {total['written']} are written "
           f"answers and {total['skipped']} can't run unattended. Most ran on the free local "
           f"model `qwen3.5:9b`; the Claude-only exercises ran on `claude-sonnet-5`. "
           f"Per-exercise results: [EXERCISE_INDEX.md](EXERCISE_INDEX.md).", "",
           "| Chapter | Exercises | ✔ Passed | ✘ Failed | Written answer | Skipped | Pass rate |",
           "| --- | ---: | ---: | ---: | ---: | ---: | ---: |"]
    for title, n, t in rows:
        r = t["passed"] + t["failed"]
        rate = f"{100 * t['passed'] / r:.0f}%" if r else "—"
        out.append(f"| {title} | {n} | {t['passed']} | {t['failed']} | {t['written']} | "
                   f"{t['skipped'] + t['not run']} | {rate} |")
    out.append(f"| **Total** | **{sum(n for _, n, _ in rows)}** | **{total['passed']}** | "
               f"**{total['failed']}** | **{total['written']}** | "
               f"**{total['skipped'] + total['not run']}** | "
               f"**{100 * total['passed'] / max(ran, 1):.1f}%** |")
    if fails:
        out += ["", "Failed: " + "; ".join(fails) + "."]
    out.append(END)
    return "\n".join(out)


def update_readme(res):
    readme = KIT / "README.md"
    text = readme.read_text(encoding="utf-8")
    if BEGIN not in text:
        raise SystemExit(f"README.md has no {BEGIN} ... {END} block to fill")
    start, end = text.index(BEGIN), text.index(END) + len(END)
    readme.write_text(text[:start] + results_table(res) + text[end:], encoding="utf-8")


if __name__ == "__main__":
    res = results()
    write_index(res, solution_files())
    update_readme(res)
    print("wrote EXERCISE_INDEX.md and the results table in README.md")
